# Generated by Django 4.0 on 2023-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
