# Generated by Django 4.0 on 2023-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_image_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
