# Generated by Django 4.0 on 2023-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_hit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
