# Generated by Django 4.0 on 2023-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
